---
name: first-ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  some-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello world"
